const state={street:'flop',pot:3750,currentBet:500,raiseAmount:1500,activeSeatId:'hero',timer:72,seats:[{id:'1',initial:'N',name:'NIKOLAY',stack:12450,bet:500},{id:'2',initial:'D',name:'DMITRY',stack:8920,bet:500},{id:'3',initial:'A',name:'ALEXEY',stack:15780,bet:1000},{id:'4',initial:'S',name:'SERGEY',stack:9300,bet:500},{id:'5',initial:'M',name:'MAXIM',stack:10950,bet:0},{id:'hero',initial:'V',name:'YOU',stack:11250,bet:0}]};
const cards={preflop:[],flop:[['A','spade','black'],['K','heart','red'],['Q','club','black']],turn:[['A','spade','black'],['K','heart','red'],['Q','club','black'],['7','diamond','red']],river:[['A','spade','black'],['K','heart','red'],['Q','club','black'],['7','diamond','red'],['2','spade','black']]};
const streets=['preflop','flop','turn','river'];
const suit={spade:'♠',heart:'♥',club:'♣',diamond:'♦'};
const money=v=>new Intl.NumberFormat('ru-RU').format(v);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function boot(){document.querySelector('.top-hud')?.classList.add('is-hidden');ensureHud();ensureSeats();ensureActions();render();setInterval(tickTimer,1000);}
function ensureHud(){const stage=document.querySelector('.room-stage');if(!stage||document.querySelector('.table-info'))return;const info=el('aside','table-info');[['NL Holdem',''],['Blinds','50 / 100'],['Ante','0'],['Room','AURUM Exclusive'],['Hand ID','#7845123']].forEach(r=>{const row=el('div','info-row');row.append(el('span','info-label',r[0]),el('strong','info-value',r[1]));info.append(row);});const tools=el('aside','utility-bar');['⚙','ⓘ','🔊','⛶'].forEach(t=>tools.append(el('button','tool-btn',t)));tools.append(el('button','leave-btn','LEAVE TABLE'));stage.append(info,tools);}
function ensureSeats(){const root=document.querySelector('.table-overlay');if(!root)return;state.seats.forEach(s=>{let node=document.querySelector(`[data-seat="${s.id}"]`);if(!node){node=el('div');node.dataset.seat=s.id;root.append(node);}node.className=`seat seat-${s.id}`;});}
function ensureActions(){const bar=document.querySelector('.action-bar');if(!bar)return;bar.replaceChildren();[['fold','FOLD','action danger'],['call','CALL 500','action primary'],['raise','RAISE TO 1 500','action gold']].forEach(a=>{const b=el('button',a[2],a[1]);b.dataset.action=a[0];bar.append(b);});const amount=el('div','raise-control');const minus=el('button','amount-btn','−');minus.dataset.action='minus';const value=el('div','amount-value','1 500');const plus=el('button','amount-btn','+');plus.dataset.action='plus';amount.append(minus,value,plus);bar.append(amount);bar.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.action)));}
function render(){document.querySelector('#potValue').textContent=money(state.pot);document.querySelector('#streetValue').textContent=state.street.toUpperCase();renderCards();renderSeats();const call=document.querySelector('[data-action="call"]');if(call)call.textContent='CALL '+money(state.currentBet);const raise=document.querySelector('[data-action="raise"]');if(raise)raise.textContent='RAISE TO '+money(state.raiseAmount);const val=document.querySelector('.amount-value');if(val)val.textContent=money(state.raiseAmount);}
function renderCards(){const root=document.querySelector('#communitySlots');root.replaceChildren();const list=cards[state.street]||[];for(let i=0;i<5;i++){const slotEl=el('div','community-anchor');const c=list[i];if(c){const card=el('div','playing-card '+(c[2]==='red'?'red':'black'));card.append(el('span','rank top',c[0]),el('span','suit',suit[c[1]]),el('span','rank bottom',c[0]));slotEl.append(card);}else slotEl.classList.add('empty');root.append(slotEl);}}
function renderSeats(){state.seats.forEach(s=>{const node=document.querySelector(`[data-seat="${s.id}"]`);if(!node)return;node.classList.toggle('is-active',s.id===state.activeSeatId);node.style.setProperty('--timer',state.timer+'%');node.replaceChildren();const avatar=el('div','seat-avatar',s.initial);const info=el('div','seat-info');info.append(el('div','seat-name',s.name),el('div','seat-stack',money(s.stack)));node.append(avatar,info);if(s.bet>0)node.append(el('div','seat-bet','BET '+money(s.bet)));});}
function tickTimer(){state.timer-=1;if(state.timer<0)state.timer=100;renderSeats();}
function act(action){const hero=state.seats.find(s=>s.id==='hero');if(!hero)return;if(action==='minus')state.raiseAmount=Math.max(state.currentBet*2,state.raiseAmount-100);if(action==='plus')state.raiseAmount+=100;if(action==='call'){hero.stack=Math.max(0,hero.stack-state.currentBet);hero.bet+=state.currentBet;state.pot+=state.currentBet;}if(action==='raise'){const amount=state.raiseAmount;hero.stack=Math.max(0,hero.stack-amount);hero.bet+=amount;state.pot+=amount;state.currentBet=amount;}render();}
document.querySelector('#streetValue')?.addEventListener('click',()=>{const idx=streets.indexOf(state.street);state.street=streets[(idx+1)%streets.length];render();});
boot();
