const state={street:'flop',pot:3750,currentBet:500,raiseAmount:1500,activeSeatId:'hero',timer:72,seats:[{id:'1',initial:'N',name:'NIKOLAY',stack:12450,bet:500},{id:'2',initial:'D',name:'DMITRY',stack:8920,bet:500},{id:'3',initial:'A',name:'ALEXEY',stack:15780,bet:1000},{id:'4',initial:'S',name:'SERGEY',stack:9300,bet:500},{id:'5',initial:'M',name:'MAXIM',stack:10950,bet:0},{id:'hero',initial:'V',name:'YOU',stack:11250,bet:0}]};
const cards={preflop:[],flop:[['A','spade','black'],['K','heart','red'],['Q','club','black']],turn:[['A','spade','black'],['K','heart','red'],['Q','club','black'],['7','diamond','red']],river:[['A','spade','black'],['K','heart','red'],['Q','club','black'],['7','diamond','red'],['2','spade','black']]};
const streets=['preflop','flop','turn','river'];
const suit={spade:'♠',heart:'♥',club:'♣',diamond:'♦'};
const money=v=>new Intl.NumberFormat('ru-RU').format(v);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};

let CARD_CAL={community:[]};
let cardCalibrated=false;
let warpedCards=[];
let cardCalOverlay=null;
let cardCalMode=false;
let cardCalSlot=0;
let cardCalPts=[];
let cardCalWork=[];
const CARD_CAL_KEY='aurum_card_calib_v1';
const CARD_CAL_CORNERS=['верхний левый угол','верхний правый угол','нижний левый угол','нижний правый угол'];

function boot(){document.querySelector('.top-hud')?.classList.add('is-hidden');ensureHud();ensureSeats();ensureActions();injectCardCalStyles();initCardCalibrator();render();setInterval(tickTimer,1000);window.addEventListener('resize',()=>{if(cardCalibrated)renderCards();});}
function ensureHud(){const stage=document.querySelector('.room-stage');if(!stage||document.querySelector('.table-info'))return;const info=el('aside','table-info');[['NL Holdem',''],['Blinds','50 / 100'],['Ante','0'],['Room','AURUM Exclusive'],['Hand ID','#7845123']].forEach(r=>{const row=el('div','info-row');row.append(el('span','info-label',r[0]),el('strong','info-value',r[1]));info.append(row);});const tools=el('aside','utility-bar');['⚙','ⓘ','🔊','⛶'].forEach(t=>tools.append(el('button','tool-btn',t)));tools.append(el('button','leave-btn','LEAVE TABLE'));stage.append(info,tools);}
function ensureSeats(){const root=document.querySelector('.table-overlay');if(!root)return;state.seats.forEach(s=>{let node=document.querySelector(`[data-seat="${s.id}"]`);if(!node){node=el('div');node.dataset.seat=s.id;root.append(node);}node.className=`seat seat-${s.id}`;});}
function ensureActions(){const bar=document.querySelector('.action-bar');if(!bar)return;bar.replaceChildren();[['fold','FOLD','action danger'],['call','CALL 500','action primary'],['raise','RAISE TO 1 500','action gold']].forEach(a=>{const b=el('button',a[2],a[1]);b.dataset.action=a[0];bar.append(b);});const amount=el('div','raise-control');const minus=el('button','amount-btn','−');minus.dataset.action='minus';const value=el('div','amount-value','1 500');const plus=el('button','amount-btn','+');plus.dataset.action='plus';amount.append(minus,value,plus);bar.append(amount);bar.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.action)));}
function render(){document.querySelector('#potValue').textContent=money(state.pot);document.querySelector('#streetValue').textContent=state.street.toUpperCase();renderCards();renderSeats();const call=document.querySelector('[data-action="call"]');if(call)call.textContent='CALL '+money(state.currentBet);const raise=document.querySelector('[data-action="raise"]');if(raise)raise.textContent='RAISE TO '+money(state.raiseAmount);const val=document.querySelector('.amount-value');if(val)val.textContent=money(state.raiseAmount);}
function renderCards(){const root=document.querySelector('#communitySlots');if(!root)return;clearWarpedCards();root.replaceChildren();if(cardCalMode)return;const list=cards[state.street]||[];const useCal=cardCalibrated&&CARD_CAL.community&&CARD_CAL.community.length===5;for(let i=0;i<5;i++){const c=list[i];if(useCal){if(c){const card=cardEl(c);card.classList.add('standalone-card');document.querySelector('.room-stage').append(card);warpedCards.push(card);warpInto(card,stageQuad(CARD_CAL.community[i]));}continue;}const slotEl=el('div','community-anchor');if(c){slotEl.append(cardEl(c));}else slotEl.classList.add('empty');root.append(slotEl);}}
function cardEl(c){const card=el('div','playing-card '+(c[2]==='red'?'red':'black'));card.append(el('span','rank top',c[0]),el('span','suit',suit[c[1]]),el('span','rank bottom',c[0]));return card;}
function clearWarpedCards(){warpedCards.forEach(n=>n.remove());warpedCards=[];}
function renderSeats(){state.seats.forEach(s=>{const node=document.querySelector(`[data-seat="${s.id}"]`);if(!node)return;node.classList.toggle('is-active',s.id===state.activeSeatId);node.style.setProperty('--timer',state.timer+'%');node.replaceChildren();const avatar=el('div','seat-avatar',s.initial);const info=el('div','seat-info');info.append(el('div','seat-name',s.name),el('div','seat-stack',money(s.stack)));node.append(avatar,info);if(s.bet>0)node.append(el('div','seat-bet','BET '+money(s.bet)));});}
function tickTimer(){state.timer-=1;if(state.timer<0)state.timer=100;renderSeats();}
function act(action){const hero=state.seats.find(s=>s.id==='hero');if(!hero)return;if(action==='minus')state.raiseAmount=Math.max(state.currentBet*2,state.raiseAmount-100);if(action==='plus')state.raiseAmount+=100;if(action==='call'){hero.stack=Math.max(0,hero.stack-state.currentBet);hero.bet+=state.currentBet;state.pot+=state.currentBet;}if(action==='raise'){const amount=state.raiseAmount;hero.stack=Math.max(0,hero.stack-amount);hero.bet+=amount;state.pot+=amount;state.currentBet=amount;}render();}

function stageQuad(q){const r=document.querySelector('.room-stage').getBoundingClientRect();return q.map(p=>[p[0]*r.width/1600,p[1]*r.height/900]);}
function adj(m){return[m[4]*m[8]-m[5]*m[7],m[2]*m[7]-m[1]*m[8],m[1]*m[5]-m[2]*m[4],m[5]*m[6]-m[3]*m[8],m[0]*m[8]-m[2]*m[6],m[2]*m[3]-m[0]*m[5],m[3]*m[7]-m[4]*m[6],m[1]*m[6]-m[0]*m[7],m[0]*m[4]-m[1]*m[3]];}
function mulmm(a,b){const c=[];for(let i=0;i<3;i++)for(let j=0;j<3;j++){let s=0;for(let k=0;k<3;k++)s+=a[3*i+k]*b[3*k+j];c[3*i+j]=s;}return c;}
function mulmv(m,v){return[m[0]*v[0]+m[1]*v[1]+m[2]*v[2],m[3]*v[0]+m[4]*v[1]+m[5]*v[2],m[6]*v[0]+m[7]*v[1]+m[8]*v[2]];}
function basis(x1,y1,x2,y2,x3,y3,x4,y4){const m=[x1,x2,x3,y1,y2,y3,1,1,1];const v=mulmv(adj(m),[x4,y4,1]);return mulmm(m,[v[0],0,0,0,v[1],0,0,0,v[2]]);}
function proj(s1x,s1y,s2x,s2y,s3x,s3y,s4x,s4y,d1x,d1y,d2x,d2y,d3x,d3y,d4x,d4y){const s=basis(s1x,s1y,s2x,s2y,s3x,s3y,s4x,s4y);const d=basis(d1x,d1y,d2x,d2y,d3x,d3y,d4x,d4y);return mulmm(d,adj(s));}
function warpInto(node,q){node.style.position='absolute';node.style.inset='auto';node.style.left='0';node.style.top='0';node.style.right='auto';node.style.bottom='auto';node.style.width='100px';node.style.height='140px';node.style.transformOrigin='0 0';const w=100,h=140;const t=proj(0,0,w,0,0,h,w,h,q[0][0],q[0][1],q[1][0],q[1][1],q[2][0],q[2][1],q[3][0],q[3][1]);for(let i=0;i<9;i++)t[i]=t[i]/t[8];node.style.transform='matrix3d('+[t[0],t[3],0,t[6],t[1],t[4],0,t[7],0,0,1,0,t[2],t[5],0,t[8]].join(',')+')';}

function initCardCalibrator(){try{const raw=localStorage.getItem(CARD_CAL_KEY)||localStorage.getItem('aurum_calib');if(raw){const data=JSON.parse(raw);const community=Array.isArray(data)?data:data.community;if(community&&community.length===5){CARD_CAL={community};cardCalibrated=true;}}}catch(e){}createCardCalOverlay();document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='c'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();openCardCal();}if(e.key==='Escape'&&cardCalMode)closeCardCal();});if(cardCalibrated)renderCards();}
function createCardCalOverlay(){const stage=document.querySelector('.room-stage');if(!stage||cardCalOverlay)return;cardCalOverlay=el('div','card-cal-overlay');cardCalOverlay.innerHTML='<svg class="card-cal-svg" viewBox="0 0 1600 900" preserveAspectRatio="none"></svg><div class="card-cal-panel"><b class="card-cal-title"></b><span class="card-cal-hint"></span><div class="card-cal-buttons"><button data-cal="undo">↶ точку</button><button data-cal="restart">слот заново</button><button data-cal="close">выход</button></div><textarea class="card-cal-out" readonly></textarea><div class="card-cal-buttons"><button data-cal="copy">скопировать JSON</button><button data-cal="clear">очистить</button></div><small>Dev mode: C — калибровка карт, Esc — выход</small></div>';stage.append(cardCalOverlay);cardCalOverlay.addEventListener('click',e=>{if(!cardCalMode||e.target.closest('.card-cal-panel'))return;const r=stage.getBoundingClientRect();const x=(e.clientX-r.left)*1600/r.width;const y=(e.clientY-r.top)*900/r.height;cardCalClick(x,y);});cardCalOverlay.querySelector('[data-cal="undo"]').onclick=()=>{cardCalPts.pop();drawCardCal();updateCardCalUI();};cardCalOverlay.querySelector('[data-cal="restart"]').onclick=()=>{cardCalPts=[];drawCardCal();updateCardCalUI();};cardCalOverlay.querySelector('[data-cal="close"]').onclick=closeCardCal;cardCalOverlay.querySelector('[data-cal="copy"]').onclick=()=>{const out=cardCalOverlay.querySelector('.card-cal-out');out.select();navigator.clipboard?.writeText(out.value).catch(()=>document.execCommand('copy'));};cardCalOverlay.querySelector('[data-cal="clear"]').onclick=()=>{CARD_CAL={community:[]};cardCalibrated=false;try{localStorage.removeItem(CARD_CAL_KEY);localStorage.removeItem('aurum_calib');}catch(e){}clearWarpedCards();closeCardCal();renderCards();};}
function openCardCal(){cardCalMode=true;cardCalSlot=0;cardCalPts=[];cardCalWork=[];clearCardCalPreviews();cardCalOverlay.classList.add('show');cardCalOverlay.querySelector('.card-cal-out').classList.remove('show');drawCardCal();updateCardCalUI();renderCards();}
function closeCardCal(){cardCalMode=false;cardCalOverlay?.classList.remove('show');clearCardCalPreviews();renderCards();}
function cardCalClick(x,y){if(cardCalSlot>=5)return;cardCalPts.push([Math.round(x*10)/10,Math.round(y*10)/10]);if(cardCalPts.length===4){cardCalWork[cardCalSlot]=cardCalPts.slice();previewCardCalSlot(cardCalWork[cardCalSlot]);cardCalSlot++;cardCalPts=[];if(cardCalSlot>=5)finishCardCal();}drawCardCal();updateCardCalUI();}
function finishCardCal(){CARD_CAL={community:cardCalWork.slice()};cardCalibrated=true;try{localStorage.setItem(CARD_CAL_KEY,JSON.stringify(CARD_CAL));}catch(e){}const out=cardCalOverlay.querySelector('.card-cal-out');out.value=JSON.stringify(CARD_CAL,null,2);out.classList.add('show');clearCardCalPreviews();renderCards();}
function updateCardCalUI(){const done=cardCalSlot>=5;cardCalOverlay.querySelector('.card-cal-title').textContent=done?'Готово ✓':'Слот '+(cardCalSlot+1)+' из 5';cardCalOverlay.querySelector('.card-cal-hint').textContent=done?'Координаты сохранены в localStorage. Скопируй JSON на всякий случай.':'Кликни '+CARD_CAL_CORNERS[cardCalPts.length]+' слота';}
function drawCardCal(){const svg=cardCalOverlay.querySelector('.card-cal-svg');let s='';cardCalWork.forEach(q=>{s+='<polygon points="'+q.map(p=>p.join(',')).join(' ')+'" fill="rgba(233,201,122,.10)" stroke="#e9c97a" stroke-width="2"/>';});if(cardCalPts.length>1)s+='<polyline points="'+cardCalPts.map(p=>p.join(',')).join(' ')+'" fill="none" stroke="#e9c97a" stroke-width="1.5" stroke-dasharray="5 4"/>';cardCalPts.forEach(p=>{s+='<circle cx="'+p[0]+'" cy="'+p[1]+'" r="7" fill="#e9c97a" stroke="#1a1206" stroke-width="2"/>';});svg.innerHTML=s;}
function previewCardCalSlot(q){const card=cardEl(['A','spade','black']);card.classList.add('standalone-card','card-cal-preview');cardCalOverlay.append(card);warpInto(card,stageQuad(q));}
function clearCardCalPreviews(){cardCalOverlay?.querySelectorAll('.card-cal-preview').forEach(n=>n.remove());}
function injectCardCalStyles(){if(document.querySelector('#cardCalStyles'))return;const style=el('style');style.id='cardCalStyles';style.textContent='.standalone-card{width:100px;height:140px;z-index:6;pointer-events:none}.card-cal-overlay{position:absolute;inset:0;z-index:50;display:none;pointer-events:auto}.card-cal-overlay.show{display:block}.card-cal-svg{position:absolute;inset:0;width:100%;height:100%;background:rgba(0,0,0,.12)}.card-cal-panel{position:absolute;right:18px;top:18px;width:310px;padding:14px;border:1px solid rgba(233,201,122,.45);border-radius:14px;background:rgba(5,4,3,.86);box-shadow:0 18px 50px rgba(0,0,0,.45);color:#f4e8cf;font:13px Inter,system-ui,sans-serif}.card-cal-title{display:block;font-size:18px;color:#f1c76d;margin-bottom:6px}.card-cal-hint{display:block;color:#dfd2b8;margin-bottom:10px}.card-cal-buttons{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.card-cal-buttons button{border:1px solid rgba(233,201,122,.35);border-radius:9px;background:rgba(18,14,9,.88);color:#f4e8cf;padding:8px 10px;cursor:pointer}.card-cal-out{display:none;width:100%;height:150px;margin-top:8px;background:#050403;color:#e9c97a;border:1px solid rgba(233,201,122,.25);border-radius:10px;padding:8px;font:11px ui-monospace,monospace}.card-cal-out.show{display:block}.card-cal-panel small{color:#9c927c}.card-cal-preview{z-index:55!important;opacity:.88}';document.head.append(style);}

document.querySelector('#streetValue')?.addEventListener('click',()=>{const idx=streets.indexOf(state.street);state.street=streets[(idx+1)%streets.length];render();});
boot();
