const state={street:'flop',pot:3750,currentBet:500,seats:[{id:'1',name:'Player 1',stack:12450,bet:500},{id:'2',name:'Player 2',stack:9100,bet:500},{id:'3',name:'Player 3',stack:15700,bet:0},{id:'4',name:'Player 4',stack:8800,bet:500},{id:'hero',name:'You',stack:12000,bet:500}]};
const cards={preflop:[],flop:[['A','♠','black'],['K','♥','red'],['7','♣','black']],turn:[['A','♠','black'],['K','♥','red'],['7','♣','black'],['10','♦','red']],river:[['A','♠','black'],['K','♥','red'],['7','♣','black'],['10','♦','red'],['2','♠','black']]};
const streets=['preflop','flop','turn','river'];
const money=v=>new Intl.NumberFormat('ru-RU').format(v);
function render(){document.querySelector('#potValue').textContent=money(state.pot);document.querySelector('#streetValue').textContent=state.street.toUpperCase();const root=document.querySelector('#communitySlots');root.replaceChildren();const list=cards[state.street]||[];for(let i=0;i<5;i++){const item=list[i];const el=document.createElement('div');if(item){el.className='card '+(item[2]==='red'?'red':'');el.textContent=item[0]+item[1];}else{el.className='card-slot';}root.appendChild(el);}for(const seat of state.seats){const el=document.querySelector(`[data-seat="${seat.id}"]`);if(!el)continue;el.dataset.name=seat.name;el.dataset.stack='STACK '+money(seat.stack);el.querySelector('.bet')?.remove();if(seat.bet>0){const bet=document.createElement('div');bet.className='bet';bet.textContent='BET '+money(seat.bet);el.appendChild(bet);}}document.querySelector('[data-action="call"]').textContent='Call '+money(state.currentBet);}
function act(action){const hero=state.seats.find(s=>s.id==='hero');if(!hero)return;if(action==='call'){hero.stack=Math.max(0,hero.stack-state.currentBet);hero.bet+=state.currentBet;state.pot+=state.currentBet;}if(action==='raise'){const amount=state.currentBet*3;hero.stack=Math.max(0,hero.stack-amount);hero.bet+=amount;state.pot+=amount;state.currentBet=amount;}render();}
document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>act(btn.dataset.action)));
document.querySelector('#streetValue')?.addEventListener('click',()=>{const idx=streets.indexOf(state.street);state.street=streets[(idx+1)%streets.length];render();});
render();
